# Set port to another value other than '8080' to not clash with the gateway server.
server:
  port: 8081

# Register self as a client to Eureka server.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Must match the name of the configuration files stored in the config server. Includes profile specific configuration files.
spring:
  application:
    name: booking-app

# Defaults to 'http://localhost:8888' if discovery is not enabled.
  config:
    import: 'optional:configserver:'
    
# Use the Eureka server to find other config server instances so that URL does not have to be set in 'spring.config.import'.
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
